[package]
name = "platformer"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "platformer"
publish = false

[dependencies]
aurora-engine = { workspace = true }
glam = { workspace = true }
log = { workspace = true }
winit = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
wasm-bindgen = { workspace = true }
